
const cards =[{
    'id': '1',
    'letter': 'Α', 
    'answer':'Alpha',
    'phonetic':'(al-fah)'
},
 {
    'id':2,
    'letter':'Β',     
    'answer':'Beta',
    'phonetic':'(bay-tah)'
 },     
{
    'id':3,
    'letter':'Γ',
    'answer':'Gamma',
    'phonetic':'(gam-ah)'
},      
{
    'id':4,
    'letter':'Δ',
    'answer':'Delta',
    'phonetic':'(del-ta)'
},      
{
    'id':5,
    'letter':'Ε',
    'answer':'Epsilon',
    'phonetic':'(ep-si-lon)'
},      
{
    'id':6,
    'letter':'Ζ',
    'answer':'Zeta',
    'phonetic':'(zay-tah)'
},     
{
    'id':7,
    'letter':'Η',
    'answer':'Eta',
    'phonetic':'(ay-tah)'
},      
{
    'id':8,
    'letter':'Θ',
    'answer':'Theta',
    'phonetic':'(thay-tah)'
},      
{
    'id':9,
    'letter':'Ι',
    'answer':'Iota',
    'phonetic':'(eye-o-tah)'
},      
{
    'id':10,
    'letter':'Κ',
    'answer':'Kappa',
    'phonetic':'(cap-pah)'
},      
{
    'id':11,
    'letter':'Λ',
    'answer':'Lambda',
     'phonetic':'(lamb-dah)'
},      
{
    'id':12,
    'letter':'Μ',
    'answer':'Mu',
    'phonetic':'(mew)'
 },      
{
    'id':13,
    'letter':'Ν',
    'answer':'Nu',
    'phonetic':'(new)'
},      
{
    'id':14,
    'letter':'Ξ',
    'answer':'Xi',
    'phonetic':'(zz-eye)'
},      
{
    'id':15,
    'letter':'Ο',
    'answer':'Omicron',
    'phonetic':'(om-e-cron)'
},      
{
    'id':16,
    'letter':'Π',
    'answer':'Pi',
    'phonetic':'(pie)'
},      
{
    'id':17,
    'letter':'Ρ',
    'answer':'Rho', 
    'phonetic':'(roe)'
},      
{
     'id':18,
     'letter':'Σ',
     'answer':'Sigma',
     'phonetic':'(sig-mah)'
},      
{
    'id':19,
    'letter':'Τ',
    'answer':'Tau',
    'phonetic':'(taw)'
},      
{
    'id':20,
    'letter':'Υ',
    'answer':'Upsilon',
    'phonetic':'(opp-si-lon)'
},      
{
    'id':21,
    'letter':'Φ',
    'answer':'Phi',
    'phonetic':'(fie)'
},      
{
    'id':22,
    'letter':'Χ',
    'answer':'Chi',
    'phonetic':'(k-eye)'
},      
{
    'id':23,
    'letter':'Ψ',
    'answer':'Psi',
    'phonetic':'(sigh)'
},      
{
    'id':24,
    'letter':'Ω',
    'answer':'Omega',
    'phonetic':'(o-may-gah)'
}      

]
 export default cards;